version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - 5431:5432
    volumes:
      - ../dkdata/postgres:/var/lib/postgresql/data
  web:
    image: {{name}}
    container_name: {{name}}
    build: .
    command: start_dev.sh
    # command: sleep 999999999
    environment:
      - DJANGO_DB_HOST=db
    depends_on:
      - db
    ports:
      - '8000:8000'
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ../..:/app
  nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ../nginx/default_local:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
