version: '3'
services:
  {{name}}:
    image: ${TEST_IMAGE}
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
  db:
    image: "postgres:9.6-alpine"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=app
